---
title: "EDS 221: day 8 interactive"
format: html
editor_options: 
  chunk_output_type: console
---
# load packages
```{r}
# General use packages:
library(tidyverse)
library(here)
library(janitor)

# Specifically for plots:
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)

# And for another dataset we'll explore:
library(gapminder)

# Spatial
library(sf)
```

# read in data
```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))
```

# plots
```{r}
# ggplot essential pieces (data, aes(what to plot), type of graph), 3 ways (that do the same thing):

# like this
ggplot(data = lizards, aes(x = total_length, y = weight)) +  # defined the data and aestetics for the entire plot
  geom_point()

# or like this
ggplot(data = lizards) +  # defined the data for the plot
  geom_point(aes(x = total_length, y = weight))  # and define aesthetics for each line independently

# or like this!
ggplot() +   # what you put in here will be applied to your entire graphic 
  geom_point(data = lizards, aes(x = total_length, y = weight))   # what you put in here is applied just to this layer. this syntax here where data is defined within the geometry is great for stuff like mapping

```

```{r}
# some graph types only need one variable
ggplot(data = lizards, aes(x = total_length)) +
  geom_histogram()
```

```{r}
# the type of data you are plotting will direct you to the appropriate graph type
#ex: jitter plot: one continuous and one categorical variable
ggplot(data = lizards, aes(y = common_name, x = weight)) +
  geom_jitter()
```

```{r}
# To change aesthetics of a graph based on a constant (e.g. “Make all the points BLUE”), we can add the information directly to the relevant geom_ layer
ggplot(data = lizards, aes(x = weight)) +
  geom_histogram(color = "orange",   # color is the outline
                 fill = "purple",   # fill is the well... fill lol
                 linewidth = 2,   # how wide the outline of the bar is
                 linetype = "dotted") 
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(color = "#606c38", # got these codes from coolors.co
             fill = "#dda15e",
             shape = 22,   # found online, point types have assigned numbers
             size = 3,  # size of the individual points
             alpha = 0.4)  # alpha for transparency (0 to 1, 1 being all color)
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = common_name,  # anything put within aes() is going to change                                               based on a variable
                 size = total_length),
             alpha = 0.5) +     # everything outside of aes() will not 
  scale_color_discrete(type = c("#ae2012",    # this is getting pretty advanced
                                  "#e6ccb2",
                                  "#e6ccb2",
                                  "#e6ccb2",
                                  "#e6ccb2",
                                  "#e6ccb2",
                                  "#e6ccb2"))

```

```{r}
ggplot(data = lizards, aes(x = site, y = weight)) +
  geom_jitter(aes(color = common_name)) +
  theme_light()
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  labs(x = "Total length (mm)",
       y = "Weight (g)",
       title = "Lizard size")
```

```{r}
# Faceting to make multiple panels at once. Sometimes it’s useful to split up information!
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  facet_wrap(~common_name, ncol = 3, scales = "free") +   # give one faceting variable, panels get wrapped into a grid. scales = "free" allows each panel to have their own scale
  labs(x = "Total length (mm)",
       y = "Weight (g)")
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  facet_grid(sex ~ tail)   # when you have multiple faceting variables
```

```{r}
lizards_counts <- lizards |>
  count(common_name)

# ggplot loves to put things in alphabetical order (where a = 0), but is rarely the order we want. o we use factor reorder (fct_reorder)
ggplot(data = lizards_counts, aes(y = fct_reorder(common_name, n), x = n)) +
  geom_col()   # bar chart
```

```{r}
# one mega example
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = common_name),
             size = 2) +
  theme_minimal() +
  labs(x = "Total length (mm)",
       y = "Weight (g)",
       color = "Lizard species",
       title = "Lizard size") +
  facet_wrap(~common_name, scales = "free")
```

```{r}
#one more example, make a stacked column graph of lizard species by site:
ggplot(data = lizards, aes(y = fct_infreq(common_name))) +
  geom_bar(aes(fill = site)) +  # geom_bar doesnt need a x bc it puts count on the x axis
  theme_minimal() +
  labs(x = "Lizard counts",
       y = "Species (common name)") +
  facet_grid(sex ~ tail)
```

```{r}
# scales package: break and label functions
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
    scale_x_continuous(breaks = c(0, 250, 500),  # change the scale to count by 250
                     limits = c(0, 500)) +  # from 0 to 500
  scale_y_continuous(breaks = seq(from = 0, to = 70, by = 10),  # count by 10
                     limits = c(0,70)) +  # from 0 to 70
  theme_light()
```

```{r}
lizards_counts <- lizards |>
  mutate(date = lubridate::mdy(date)) |>
  count(date)

ggplot(data = lizards_counts, aes(x = date, y = n)) +
  geom_line() +
  scale_x_date(breaks = scales::breaks_pretty()) +
#  scale_x_date(breaks = scales::breaks_width("3 years"),
 #              labels = scales::label_date("%Y")) +
  labs(x = "Date",
       y = "Number of lizards (n)")
```

```{r}
# use scale functions to update color gradients
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = total_length)) + 
  scale_color_steps2(low = "green", mid = "white", high = "red", midpoint = 150, 
                     breaks = c(50, 75, 150, 180, 220, 280))
  #scale_color_steps(low = "red", high = "black")# bin the color gradient into a few colors
 # scale_color_gradientn(colors = c("orange", "red", "purple", "navy", "black")) # pick as many colors as you want to make the gradient
 # scale_color_gradient(low = "red", high = "navy") # make a gradient from one color to another

```

```{r}
p <- ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point()

p + 
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "red"),
        plot.background = element_rect(fill = "pink"),
        text = element_text(size = 12, family = "serif"),
        axis.text.x = element_text(color = "blue"),
        axis.text.y = element_text(color = "green"),
        panel.background = element_rect(color = "purple", fill = "yellow"))
  
```

```{r}
p +
  geom_hline(yintercept = mean(lizards$weight), color = "blue", linetype = "dashed") +
  geom_vline(xintercept = 100, color = "red") +
  annotate("text", x = 100, y = 50, label = "COOL!", color = "purple") +
  annotate("text", x = 350, y = mean(lizards$weight) +2 , label = "Mean weight")
```

ˆ
```{r}
mono <- read_csv(here("data_tidy", "mono.csv"))

ggplot(data = mono, aes(x = year, y = lake_level)) +
 
  geom_rect(aes(xmin = 1941,
                     xmax = 1983,
                     ymin = 6350,
                     ymax = 6440),
            fill = "grey90") + 
  geom_line() +
  labs(x = "Year", 
       y = "Lake surface level\n(feet above sea level)\n",
       title = "Mono Lake (1850 - 2017)", 
       caption = "Data: Mono Basin Clearinghouse") +  #\n...\n allows for text on a seperate line
  scale_y_continuous(limits = c(6350, 6440),
                     breaks = c(6370, 6400, 6430),
                     labels = scales::label_comma()) +  # express label with tick
  scale_x_continuous(limits = c(1850, 2020),
                     breaks = seq(1850, 2010, by = 20),
                     expand = c(0,0)) +
  geom_hline(yintercept = 6360, linetype = "dashed") +
  annotate("text", x = 1910, y = 6365,
           label = "Decreased shrimp abundance expected\n(6,360 feet above sea level)") +
  annotate("text", x = 1962, y = 6435,
           label = "Unrestricted diversions\n(1941 - 1983)",
           size = 3) +
  theme_minimal()
  
```



